const fs = require('node:fs');
const path = require('node:path');
const sharp = require('sharp');
(async () => {
  const { products } = await import('../src/data/products.js');
  const inputs = [...products.map(p => [p.id, p.image]), ['workshop', '/assets/workshop.png'], ['oak', '/assets/woods/oak.png'], ['walnut', '/assets/woods/walnut.png'], ['sapele', '/assets/woods/sapele.png']];
  const destination = path.join(process.cwd(), 'public/assets/optimized');
  fs.mkdirSync(destination, { recursive: true });
  const images = {};
  let before = 0;
  let after = 0;
  for (const [id, source] of inputs) {
    const input = path.join(process.cwd(), 'public', source);
    before += fs.statSync(input).size;
    const variants = [];
    for (const width of [600, 1200]) {
      const filename = `${id}-${width}.webp`;
      const result = await sharp(input).rotate().resize({ width, withoutEnlargement: true }).webp({ quality: 82 }).toFile(path.join(destination, filename));
      variants.push({ src: `/assets/optimized/${filename}`, width: result.width });
      if (width === 1200) after += result.size;
    }
    images[source] = variants;
  }
  fs.writeFileSync('src/data/image-variants.js', '// Generated by scripts/optimize-images.cjs. Original images are preserved.\nexport const imageVariants = ' + JSON.stringify(images, null, 2) + ';\n');
  console.log(JSON.stringify({ images: inputs.length, originalBytes: before, optimizedLargeBytes: after, savedPercent: Math.round((1 - after / before) * 100) }));
})().catch(error => { console.error(error); process.exitCode = 1; });
